# fly.toml app configuration file generated for the-treehouse on 2025-03-20T13:52:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-treehouse'
primary_region = 'sea'

[build]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    timeout = "2s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
